CREATE DATABASE MyThirdDB ON PRIMARY
(NAME = MyThirdDB_Data,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\MyThirdDBData.mdf',
SIZE = 8MB,
MAXSIZE = 10MB,
FILEGROWTH = 10%)

LOG ON
(NAME = MyThirdDB_Log,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER1\MSSQL\DATA\MyThirdDBLog.ldf',
SIZE = 1MB,
MAXSIZE = 5MB,
FILEGROWTH = 10%)